pub const PYTHON_CODE:&str = r#"def main():
    """
    This is a sample Python code generated by Keel Python Project Creator.
    You can modify this code to fit your needs.
    """
    print("Hello, world!")

if __name__ == "__main__":
    main()
"#;

pub const TODO_SAMPLE: &str = r#"# TODO

Add your tasks, feature ideas, bug fixes, and other actionable items here. This file is intended to help you track progress and organize your work.

## Guidelines:
- Use checkboxes (`- [ ]`) for tasks that are not yet started.
- Use completed checkboxes (`- [x]`) for tasks that are done.
- Group related tasks under appropriate headings (e.g., `Features`, `Fixes`, `Refactoring`).
- Add details, deadlines, or priorities as needed.

## Template:

### Features
- [ ] Add support for [feature description].
- [ ] Implement [new functionality].

### Fixes
- [ ] Fix [bug description].
- [ ] Resolve [issue description].

### Refactoring
- [ ] Refactor [module/component] for better performance.
- [ ] Improve code readability in [file/module].

### Documentation
- [ ] Update README with [new information].
- [ ] Add comments to [file/module].

### Testing
- [ ] Write unit tests for [feature/module].
- [ ] Add integration tests for [component].

---

## Notes:
- This file is **not under version control** to avoid cluttering the repository with personal or temporary tasks.
- Regularly review and update this file to keep track of your progress.
"#;
