name: keel

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
        rust: [stable ]

    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        components: clippy,rustfmt
    - name: Run tests
      run: cargo test --verbose
    - name: Build
      run: cargo build --release
    - name: Package
      run: cargo package --allow-dirty
    - uses: actions/upload-artifact@v4
      with:
        name: keel-${{ matrix.os }}-${{ matrix.rust }}
        path: target/release/keel-${{ matrix.os }}-${{ matrix.rust }}.zip
    - name: Extract Version
      id: version
      run: |
        VERSION=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        tag: v${{ steps.version.outputs.VERSION }}
        name: "v${{ steps.version.outputs.VERSION }}"
        draft: false
        prerelease: true
        body: "Release version v${{ steps.version.outputs.VERSION }} of keel."
        artifacts: target/release/keel-*-*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
